version: "3"
services:
  frontend:
    container_name: handovertool_web
    build:
      context: ./client
      dockerfile: Dockerfile
    image: hoomand/handovertool_web
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
  backend:
    container_name: handovertool_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: hoomand/handovertool_server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/usr/src/app
