version: "3"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - ${APP_SERVER_PORT}
    environment:
      APP_SERVER_PORT: ${APP_SERVER_PORT}
      NODE_ENV: ${NODE_ENV}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes:
      - ./server:/usr/src/app/server
    command: npm run server

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client:/usr/src/app/client
    links:
      - server
    command: npm run start
