version: "3"
networks:
  hot:

services:
  server:
    networks:
      - hot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_SERVER_PORT: ${APP_SERVER_PORT}
      NODE_ENV: ${NODE_ENV}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      AWS_REGION: ${AWS_REGION}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}

  client:
    networks:
      - hot
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
